apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: elixir-k8
spec:
  replicas: 2
  selector:
      matchLabels:
          app: elixir_k8
  template:
    metadata:
      labels: 
        app: elixir_k8
    spec:
      containers:
        - name: elixir-k8
          image: aravi123/elixir_k8:datadog-v9
          ports:
            - containerPort: 8080
          env:
            - name: DD_KUBERNETES_KUBELET_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP